### ISSUE TITLE
Remote server returned error 400. Bad request

### ISSUE THREAD

**Issue by Sbzz** [novaroma-project/novaroma#11]
As the subject says. Remote server returns error 400. Bad request. 
Initially it was returning error 403, so I removed thepiratebay.vg from the list of torrent searching sites. And now error 400 comes up. 

Any fix?

**Comment by emrahyumuk** [comment]
You can change torrent services urls from settings. 

![novaroma-update-torrent-provider](https://cloud.githubusercontent.com/assets/2338849/17465055/4e518140-5cf5-11e6-941d-b867f2a37358.png)

**Comment by Tankamin** [comment]
Hello, I am getting this error and changing the source doesn't help.. everything i've tried gives the same error.. What can i do?  PS: I have never gotten Novaroma to work..

**Comment by ozoner** [comment]
I am having this same error but, after the object reference not set to an instance of an object, error, then I get error: (400) bad request.  I have no idea what to do now.  I tried various settings to point to correct urls and nothign ever seems to work.  THe program would be amazing if it wasn't so buggy.  Anywone have any ideas?
