### ISSUE TITLE
thepiratebay.vg cannot be found

### ISSUE THREAD

**Issue by mbartmon** [novaroma-project/novaroma#9]
Installed NovaRoma yesterday but cannot download anything. A popup appears with the message  The remote name could not be resolved 'thepiratebay.vg'.  This URL also cannot be found when entered directly in my browser.

**Comment by jon20ast** [comment]
Same problem for me, trying to find a way to change it

**Comment by Sbzz** [comment]
Just remove it from Novaroma Setting....check under the Services tab. You will see it there.

**Comment by XMotoGodX** [comment]
Just change it to thepiratebay.se and you should be good to go.

**Comment by emrahyumuk** [comment]
New version 0.9.9.3 is released. Critical Errors are fixed. Kickass and piratebay urls are updated. 
You can change torrent services urls from settings 

![novaroma-update-torrent-provider](https://cloud.githubusercontent.com/assets/2338849/17465055/4e518140-5cf5-11e6-941d-b867f2a37358.png)
